{"cells":[{"metadata":{},"cell_type":"markdown","source":"# A) Définitions de fonctions\n\n### Définition des entrées / sorties\n\nLes fonctions sont des objets python qui prennent en entrée un certain nombre de variables (dites variables d'entrée ou encore arguments de la fonction) et renvoie des variables de sortie (en plaçant leurs identifiants après le mot clé __return__)"},{"metadata":{"trusted":true},"cell_type":"code","source":"def mafonction(entree1,entree2):\n    ''' Code situé dans la fonction'''\n    print('nous voilà dans la fonction')\n    somme = entree1 + entree2 # Si les entrées ne sont pas des objets sommables, la fonction plantera\n    return somme # Le résultat renvoyé est la somme des 2 valeurs d'entrée de la fonction","execution_count":1,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"#### Remarque : Nous avons défini une fonction mais nous ne l'avons pas utilisé, rien ne s'est affiché. Pour l'utiliser on doit passer des valeurs dans les variables d'entrée et récupérer les sorties dans une variable également:"},{"metadata":{"trusted":true},"cell_type":"code","source":"var1 = 4\nvar2 = 6\n\nresultat = mafonction(var1,var2) # le contenu de var1 est passé dans entree1, \n# le contenu de var2 est passé dans entree2 et le contenu de la variable somme calculé dans la fonction\n# est retourné est placé dans la variable resultat","execution_count":2,"outputs":[{"output_type":"stream","text":"nous voilà dans la fonction\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"Remarque : Cette fois nous avons utilisé la fonction mais son résultat n'a pas été affiché. Il a seulement été placé dans la variable resultat. Pour l'afficher il faut le demander explicitement à python"},{"metadata":{"trusted":true},"cell_type":"code","source":"print(resultat)","execution_count":3,"outputs":[{"output_type":"stream","text":"10\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"## Erreurs classiques de définitions / manipulation de fonctions\n\n1. #### Les variables définies dans la fonction sont inaccessibles depuis l'extérieur. Pour transférer des variables contenues dans la fonction à l'extérieur, il faut les faire passer dans le return."},{"metadata":{"trusted":true},"cell_type":"code","source":"#Cas erreur 1 :  tenter d'accéder à une variable dans la fonction: \nvar1 = 4\nvar2 = 6\n\nmafonction(var1,var2) # On exécute la fonction précédente, on s'attend donc à ce que la variable \n# somme = var1 + var2 soit calculée\n\nprint(somme) # Ca ne marche pas car la variable somme n'existe que dans la fonction et non dehors","execution_count":4,"outputs":[{"output_type":"stream","text":"nous voilà dans la fonction\n","name":"stdout"},{"output_type":"stream","text":"Traceback (most recent call last):\n  File \"<input>\", line 8, in <module>\nNameError: name 'somme' is not defined\n","name":"stderr"}]},{"metadata":{},"cell_type":"markdown","source":"2. #### Les entrées de la fonction sont choisies à la définition de la fonction. Il faut que le nombre d'entrées lors de l'utilisation soit cohérent avec le nombre d'entrées lors de la définition :"},{"metadata":{"trusted":true},"cell_type":"code","source":"#Cas erreur 2 : mettre le mauvais nombre d'entrées\nresultat = mafonction(var1)","execution_count":5,"outputs":[{"output_type":"stream","text":"Traceback (most recent call last):\n  File \"<input>\", line 2, in <module>\nTypeError: mafonction() missing 1 required positional argument: 'entree2'\n","name":"stderr"}]},{"metadata":{},"cell_type":"markdown","source":"3. #### Les entrées de la fonctions doivent être compatibles avec ce qu'elle fait (si la fonction manipule des nombres, les entrées doivent être des entiers ou des flottants ...)"},{"metadata":{"trusted":true},"cell_type":"code","source":"#Cas erreur 3 Mettre des entrées non compatibles\nvar3 = 'bambou'\nmafonction(var1,var3)","execution_count":6,"outputs":[{"output_type":"stream","text":"nous voilà dans la fonction\n","name":"stdout"},{"output_type":"stream","text":"Traceback (most recent call last):\n  File \"<input>\", line 3, in <module>\n  File \"<input>\", line 4, in mafonction\nTypeError: unsupported operand type(s) for +: 'int' and 'str'\n","name":"stderr"}]},{"metadata":{},"cell_type":"markdown","source":"4. #### Lors de la définition d'une fonction, on définit ce que fait une fonction (la séquence d'instruction qu'elle contient) et les variables qu'elle prend en entrée. \n### Ces variables ne peuvent pas être des constantes."},{"metadata":{"trusted":true},"cell_type":"code","source":"#Cas 4 Définition d'une fonction avec des constantes\n\ndef fonction_plante(var,2):\n    return var","execution_count":7,"outputs":[{"output_type":"stream","text":"  File \"<input>\", line 3\n    def fonction_plante(var,2):\n                            ^\nSyntaxError: invalid syntax\n","name":"stderr"}]},{"metadata":{},"cell_type":"markdown","source":"# A') Exercices"},{"metadata":{},"cell_type":"markdown","source":"Ecrire une fonction __incr_deux(nombre)__ qui incrémente un nombre passé en argument de deux. \n\nOn rappelle qu'incrémenter une variable d'une valeur __v__ signifie que l'on ajoute __v__ à cette variable."},{"metadata":{"trusted":true},"cell_type":"code","source":"def incr_deux(nombre):\n    '''Code de la fonction à compléter'''\n    \n    return         # Variable(s) renvoyé(es) par la fonction à compléter également","execution_count":8,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Ecrire une fonction __test_grand(taille)__ qui teste si un individu est grand. \n\nLa variable __taille__ correspond à la taille d'un individu en centimètres et on considèrera qu'un individu est grand s'il mesure plus de 175cm. La fonction renverra le booléen __True__ et affichera 'voilà quelqu'un de grand' si l'individu est grand, et elle renverra __False__ et affichera 'voilà quelqu'un de pas très grand' sinon."},{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":" Ecrire une fonction __fibonacci(n)__ qui calcule le _n_-ième terme de la suite de Fibonacci (définie par $u_0 = u_1 = 1$ et $\\forall n \\geq 2$ : $u_{n} = u_{n-1}+u_{n-2}$)."},{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"# B) Jeux de test et contrôle des arguments des fonctions\n\n### Jeux de test\n\nDans le cadre du travail de l'ingénieur, il est nécessaire de vérifier et garantir que les codes rédigés produisent bien le résultat attendu. On met donc en place des __jeux de test__ qui représentent une épreuve que doit passer le code pour être considéré comme valide. Les jeux de tests prennent en général la forme suivante :\n\n1. On spécifie des entrées du programme pour lesquelles on connaît le résultat que l'ordinateur doit produire\n2. On exécute le code avec les entrées choisies\n3. On compare le résultat attendu avec les sorties produites par l'ordinateur\n4. Si les sorties sont identiques, le programme est validé. Sinon, on dit que le code ne passe pas le jeu de test et il est nécessaire de le modifier.\n\nDans de nombreux cas, il faudra se poser la question suivante : _quelles sont les entrées / sorties judicieuses pour tester mon programme_. \n\nAfin d'illustrer ce problème, on propose un jeu de test pour la fonction __incr_deux(nombre)__ définies précédemment:\n\n"},{"metadata":{"trusted":true},"cell_type":"code","source":"## Code de test pour la fonction incr_deux\n\n# Définition des entrées du programme \nentree1 = 42\nentree2 = 0\nentree3 = -42\n\n# Exécution de la fonction pour les différentes entrées\nresultat1 = incr_deux(entree1)\nresultat2 = incr_deux(entree2)\nresultat3 = incr_deux(entree3)\n\n# Stockage du résulat des tests (booléen True / False indiquant si le test est réussi)\ntest1 = resultat1 == 44\ntest2 = resultat2 == 2\ntest3 = resultat3 == -40\nif test1:\n    print('la fonction semble correcte avec des entrées numériques positives')\nif test2:\n    print('la fonction semble correcte avec l entrée nulle')\nif test3:\n    print('la fonction semble correcte avec des entrées numériques négatives')\n    \n# Affichage du résultat final du test:\ntest_final = test1 and test2 and test3 # (la fonction est correcte si tous les tests passent \n# c'est à dire que test1 == True ET test2 == True ET test3 == True)\n\nif test_final :\n    print('tous les tests passent')\nelse:\n    print('au moins un test ne passe pas')","execution_count":9,"outputs":[{"output_type":"stream","text":"au moins un test ne passe pas\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"#### Un peu plus subtil :\n\nLes tests correspondent à une suite d'instruction qui comportent un certain nombre d'entrées et produisent un résultat, on peut donc éventuellement les faire au moyen d'une fonction:"},{"metadata":{"trusted":true},"cell_type":"code","source":"def test_incr_deux(mafonction,entree,sortie):\n    '''C est une fonction qui prend en entrée une autre fonction !'''\n    test = mafonction(entree) == sortie\n    if test :\n        print(' la fonction incr_deux a un comportement correct pour l entrée',entree)\n    else:\n        print(' la fonction incr_deux a un comportement incorrect pour l entrée',entree)\n    return test\n\ntest_passe = test_incr_deux(incr_deux,3,5) # La fonction incr_deux est passée en entrée de test_incr_deux\n\n# Notez, que l'on a bien affiché le message contenu dans le print mais pas la variable booléenne test \n# que l'on a stocké dans test_passe","execution_count":10,"outputs":[{"output_type":"stream","text":" la fonction incr_deux a un comportement incorrect pour l entrée 3\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"# B') Exercices\n\nEcrire les jeux de test associés aux fonctions __test_grand(taille)__ et __fibonacci(n)__. On rappelle que les jeux de test doivent porter sur des valeurs des entrées pour lesquelles la fonction est bien définie et testeront lorsque c'est possible les cas limites."},{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"### Spécification des données attendues et assertions\n\nDans les exemples précédents, on a systématiquement supposé implicitement que les fonctions seraient utilisées _correctement_ c'est à dire qu'un utilisateur bienveillant va choisir des entrées cohérentes avec les instructions des fonctions. \n\nAfin de communiquer avec l'utilisateur, il est nécessaire d'une part de _spécifier_ le rôle d'une fonction ainsi que les contraintes que les entrées de cette fonction doivent satisfaire. La _spécification_ d'une fonction est écrite en début d'une fonction et présentée entre triple quotes : ''' spécification '''\n\n##### Exemple:"},{"metadata":{"trusted":true},"cell_type":"code","source":"def test_grand(taille):\n    '''-Entrée : taille (en centimètre) int ou float positif ou nul\n    -Sortie : booléen indiquant si la taille est supérieure à 175 cm \n    -Fonction permettant de tester si la taille en cm d un humain dépasse un\n    certain seuil'''\n    # Code de la fonction à écrire\n    \n    return","execution_count":11,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Les spécifications entre triple quotes correspondent à l'aide d'une fonction (que l'on obtient via la commande __help(nom_fonction)__ ). Il est donc important que celles-ci soit à la fois suffisamment informatives ET concises."},{"metadata":{"trusted":true},"cell_type":"code","source":"help(test_grand)","execution_count":12,"outputs":[{"output_type":"stream","text":"Help on function test_grand in module __main__:\n\ntest_grand(taille)\n    -Entrée : taille (en centimètre) int ou float positif ou nul\n    -Sortie : booléen indiquant si la taille est supérieure à 175 cm \n    -Fonction permettant de tester si la taille en cm d un humain dépasse un\n    certain seuil\n\n\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"# B'') Exercices\n\nOn souhaite calculer le terme $\\sum_{k=0}^n \\dfrac{1}{k!}$.\n\n_Ecrire les trois fonctions :_\n__inv_factorielle(n)__ qui prend en entrée un entier $n$ et calcule et renvoie le terme $\\dfrac{1}{n!}$\n\n__sum_f(f,n)__ qui prend en entrée une fonction $f$ et un entier $n$ et renvoie le terme $\\sum_{k=0}^n f(k)$\n\net __sum_facto(n)__ qui calcule $\\sum_{k=0}^n \\dfrac{1}{k!}$ en réutilisant les deux fonctions précédentes.\n\n#### On prendra soin d'écrire la spécification de chacune des fonctions "},{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Proposer des jeux de test pour chacune des fonctions précédentes, on pourra notamment tester __sum_f__ en choisissant pour fonction $f$ la fonction $f:x\\mapsto 1$."},{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Postuler la limite de la suite $u_n = \\sum_{k=0}^n \\dfrac{1}{k!}$. On pourra notamment inspecter la valeur du nombre d'euler $e$"},{"metadata":{"trusted":true},"cell_type":"code","source":"import numpy\ne = numpy.exp(1)\n","execution_count":13,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"markdown","source":"#### Pour aller plus loin :\nPour calculer __sum_facto(n)__, on peut faire appel à __sum_f(inv_factorielle,n)__. (c'est ce qui était suggéré dans l'énoncé).\n\nDans ce cas, estimer en fonction de __n__ le nombre d'opérations élémentaires (addition, produits, inversions) nécessaires pour effectuer le calcul. On pourra notamment commencer par calculer le nombre d'opérations élémentaires nécessaires pour calculer __inv_factorielle(n)__ pour en déduire celui de __sum_facto(n)__.\n\nEn remarquant que $n! = n \\cdot (n-1)!$ proposer une nouvelle implémentation de __sum_facto(n)__ qui ne nécessite cette fois que $n$ additions + $n$ multiplications. (Pour calculer $n!$, il faut réutiliser le résultat de $(n-1)!\\cdot n$ ce qui nécessite une multiplication et non pas calculer $\\prod_{k=1}^n k$ qui nécessite $n-1$ multiplications."},{"metadata":{},"cell_type":"markdown","source":"# C) Domaine de définition d'une fonction, assertions\n\nLors de la définition d'une fonction, on a vu que la spécification permet de guider l'utilisateur dans le choix des entrées. Malheureusement prévenir ne suffit pas toujours, et il est possible d'imposer des contraintes sur les variables en entrée d'une fonction. Ces contraintes sont imposées en utilisant la syntaxe:\n\n__assert condition__ \n\nOù __condition__ est une variable booléenne. Lorsque la condition prend la valeur __False__, la fonction s'arrête immédiatement en retournant une erreur __AssertionError__ (en général on dit plutôt _lever_ une erreur). Ce type d'erreur peut éventuellement être pris en compte pour que le programme puisse réagir de la bonne manière.\n\nL'écriture de conditions sur les entrées des fonctions via la commande __assert__ est au programme de CPGE. En revanche l'utilisation de l'erreur remontée ne l'est pas mais on va tout de même l'illustrer sur l'exemple ci-dessous."},{"metadata":{"trusted":true},"cell_type":"code","source":"def factorielle(n):\n    '''Entrée : n entier positif ou nul\n        Sortie : produits des entiers de 1 à n'''\n    # assert type(n) == int # On vérifie que n est bien un entier, on peut utiliser la fonction type() qui renvoie le type d'un objet\n    assert n>=0 # Puis on vérifie qu'il est bien positif\n    \n    resultat = 1 \n    for i in range(1,n+1): # La dernière valeur du range est exclue\n        resultat *= i\n    return resultat","execution_count":14,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"Inspectons ce qu'il se passe en fonction des entrées passées à cette fonction:"},{"metadata":{"trusted":true},"cell_type":"code","source":"print(factorielle(3))\nprint(factorielle(0))\nprint(factorielle(-2))","execution_count":15,"outputs":[{"output_type":"stream","text":"6\n1\n","name":"stdout"},{"output_type":"stream","text":"Traceback (most recent call last):\n  File \"<input>\", line 3, in <module>\n  File \"<input>\", line 5, in factorielle\nAssertionError\n","name":"stderr"}]},{"metadata":{},"cell_type":"markdown","source":"On retrouve bien l'erreur __AssertionError__ que l'on aurait pu détecter et réutiliser. Le code ci-dessous montre comment prendre en compte une erreur dans le code :"},{"metadata":{"trusted":true},"cell_type":"code","source":"\ndef check_fonction(mafonction,entree):\n    \n    try: # On essaie d'exécuter le code indenté ci-dessous, s'il ne plante pas tout va bien, sinon on ira exécuter \n        # le code indenté après l'instruction except\n        \n        mafonction(entree) # On essaie d'utiliser une fonction mafonction avec l'entree entree\n        print('Avec cette entree',entree, 'on n a pas eu d erreur')\n        \n    except AssertionError: # Si on a une AssertionError, les instructions indentées sous ce except vont être exécutées\n\n        print('Avec cette entree :',entree, ' on a une erreur AssertionError')\n        \n    except: # Si on a une autre erreur (pas AssertionError) les lignes indentées sous ce except vont être exécutées\n        print('Avec cette entree :',entree, ' on a une erreur imprévue !')\n    return\n","execution_count":16,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"check_fonction(factorielle,4)\ncheck_fonction(factorielle,-3)\ncheck_fonction(factorielle,'salut') # On peut prévoir ou non cette erreur en commentant / décommentant \n# la ligne assert type(n) == int dans le code de la fonction factorielle","execution_count":17,"outputs":[{"output_type":"stream","text":"Avec cette entree 4 on n a pas eu d erreur\nAvec cette entree : -3  on a une erreur AssertionError\nAvec cette entree : salut  on a une erreur imprévue !\n","name":"stdout"}]},{"metadata":{},"cell_type":"markdown","source":"# C') Exercice\n\n1. On souhaite écrire la fonction __tout_sauf_une_liste(truc)__ qui renvoie truc si ce n'est pas une liste (de type __list__) et qui lève une AssertionError sinon.\n"},{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]},{"metadata":{},"cell_type":"markdown","source":"2. Ecrire une fonction __compte_entiers(liste)__ qui compte le nombre d'entiers dans une liste passée en arguments. La fonction en entrée lèvera une AssertionError si la variable __liste__ n'est pas de type _list_.\n\nRappel : En Python une liste est une collection d'objets de types éventuellement différents que l'on déclare par la syntaxe [obj1,obj2,...,objn].\nOn peut récupérer la taille d'une __liste__ (le nombre d'objets qu'elle contient) avec l'instruction __len(liste)__ et on peut accéder à l'élément à la position __i__ (indexé à partir de __i=0__ pour le premier objet) avec la syntaxe __liste[i]__."},{"metadata":{"trusted":true},"cell_type":"code","source":"def compte_entiers(liste):\n    \n    ### A compléter\n    \n    return","execution_count":18,"outputs":[]},{"metadata":{"trusted":true},"cell_type":"code","source":"## On pourra vérifier que notre fonction passe le jeu de test suivant :\n\ndef teste_compte_entiers(fonction,entree):\n    try:\n        resultat = fonction(entree)\n    except AssertionError:\n        resultat = 'Assert erreur'\n    except:\n        resultat =  'Autre erreur'\n    return resultat\n    \ntest1 = teste_compte_entiers(compte_entiers,[3,'salut',None,4,['3',3,'piège'],3.2])==2\ntest2 = teste_compte_entiers(compte_entiers,34)=='Assert erreur'\nif test1 and test2:\n    print('la fonction passe le test')\nelse:\n    print('il te reste un peu de travail')\n    \n    ","execution_count":19,"outputs":[{"output_type":"stream","text":"il te reste un peu de travail\n","name":"stdout"}]},{"metadata":{"trusted":true},"cell_type":"code","source":"","execution_count":null,"outputs":[]}],"metadata":{"kernelspec":{"name":"python3","display_name":"Python 3","language":"python"}},"nbformat":4,"nbformat_minor":2}